### ISSUE TITLE
War file for multiple application server support

### ISSUE THREAD

**Issue by atultherajput** [vpavic-demos/spring-boot-multi-package-demo#3]
Is it possible to support multiple app servers like tomcat, jetty, jboss, WebLogic, WebSphere etc? My problem is that I don't know what application server will the client use to deploy my product. Therefore I need a generic war file which could be deployed on any server. I don't know if it is possible without creating multiple sub project like demo-package-war-wildfy.

**Comment by vpavic** [comment]
This is highly dependent on the components that you use in your project, such as WebJars that require special handling under WildFly. So for example, if you're not using WebJars the default WAR package might be enough for WildFly in your case.

The only reliable way of knowing what works where is to include deployment tests for different application servers within your project, which you can then advertise as officially supported by your product. You might use Spring Boot's [deployment tests module](https://github.com/spring-projects/spring-boot/tree/main/spring-boot-tests/spring-boot-deployment-tests) as an inspiration.
